// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3SrqMhDmis4bn8ZxKaklHiqkGWO92A4',
    appId: '1:32205103587:web:1abb4e65f529508d9040d6',
    messagingSenderId: '32205103587',
    projectId: 'movewise-2e08d',
    authDomain: 'movewise-2e08d.firebaseapp.com',
    databaseURL: 'https://movewise-2e08d-default-rtdb.firebaseio.com',
    storageBucket: 'movewise-2e08d.firebasestorage.app',
    measurementId: 'G-J1C7TS130T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOuzrtNKP4KtEk9k5UPJcPGNdifOEneqY',
    appId: '1:32205103587:android:b3e33988b33c3d4c9040d6',
    messagingSenderId: '32205103587',
    projectId: 'movewise-2e08d',
    databaseURL: 'https://movewise-2e08d-default-rtdb.firebaseio.com',
    storageBucket: 'movewise-2e08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVYJkQCsWFqosmyloNJn24bJPXglx-w4Y',
    appId: '1:32205103587:ios:b6a78e3e82b07ae09040d6',
    messagingSenderId: '32205103587',
    projectId: 'movewise-2e08d',
    databaseURL: 'https://movewise-2e08d-default-rtdb.firebaseio.com',
    storageBucket: 'movewise-2e08d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP3SrqMhDmis4bn8ZxKaklHiqkGWO92A4',
    appId: '1:32205103587:web:560fe7d0151cfb179040d6',
    messagingSenderId: '32205103587',
    projectId: 'movewise-2e08d',
    authDomain: 'movewise-2e08d.firebaseapp.com',
    databaseURL: 'https://movewise-2e08d-default-rtdb.firebaseio.com',
    storageBucket: 'movewise-2e08d.firebasestorage.app',
    measurementId: 'G-45QQ0HZG3E',
  );
}
